name: Deploy Frontend to Server

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Cache node modules
      uses: actions/cache@v4
      with:
        path: PRAGATHI-UI/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('PRAGATHI-UI/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
        
    - name: Install dependencies
      working-directory: ./PRAGATHI-UI
      run: npm ci
      
    - name: Run linting
      working-directory: ./PRAGATHI-UI
      run: npm run lint
      
    - name: Build application
      working-directory: ./PRAGATHI-UI
      run: npm run build:prod
      env:
        VITE_API_URL: ${{ secrets.VITE_API_URL }}
        
    - name: Deploy to server
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT || 22 }}
        script: |
          cd /home/sasikalavijayakumar/pragathi_server
          ./deploy-frontend.sh
          
    - name: Upload build artifacts
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT || 22 }}
        source: "PRAGATHI-UI/dist/*"
        target: "/home/sasikalavijayakumar/pragathi_server/frontend-dist"
        strip_components: 2
